import numpy as np
import pandas as pd
import streamlit as st
import altair as alt
import time

st.sidebar.markdown("Impact tracking results derived from the linking of: i) seaborne merchandise trade data for 2018 sourced from the UNCTAD Trade-and-Transport, ii) AIS data underpinning the 4th IMO GHG Study and iii) assumptions of Maritime Transport Costs (MTCs) resulting from the IMO Net-Zero Framework (NZF).")

impact_res_ex_c = [
    "source_iso_code", "source_country", "gdp_2018_wb", "vol_kg", "val_usd",
    "vol_kg_recon", "val_usd_recon", "ene_tj_recon", "co2_t_recon",
    "ets_23_usd_recon", "ets_30_usd_recon", "ets_23_pct_gdp", "ets_30_pct_gdp", 
    "bau_usd_23_recon", "bau_usd_30_recon", "bau_usd_40_recon", "bau_usd_50_recon",
    "bau_23_pct_gdp", "bau_30_pct_gdp", "bau_40_pct_gdp", "bau_50_pct_gdp", 
    "s24_usd_23_recon_del", "s24_usd_30_recon_del", "s24_usd_40_recon_del", "s24_usd_50_recon_del",
    "s24_del_23_pct_gdp", "s24_del_30_pct_gdp", "s24_del_40_pct_gdp", "s24_del_50_pct_gdp"
]
impact_res_ex_r = {
    
    # Country Stats
    "source_country":"Country",
    "gdp_2018_wb":"GDP (2018)",
    "vol_kg":"Trade Portfolio Volume (kg)", 
    "val_usd":"Trade Portfolio Value (US$)", 

    # Trade Reconstruction Stats
    "vol_kg_recon":"Reconstructed Trade Volume (kg)", 
    "val_usd_recon":"Reconstructed Trade Value (US$)", 
    "ene_tj_recon":"Reconstructed Trade Energy Demand (kg)", 
    "co2_t_recon":"Reconstructed Trade CO2 Emissions (US$)", 

    # ETS Compliance Costs
    "ets_23_usd_recon":"ETS Compliance Costs in 2023 (US$)", 
    "ets_30_usd_recon":"ETS Compliance Costs in 2030 (US$)", 
    "ets_23_pct_gdp":"ETS Compliance Costs in 2023 (%GDP)", 
    "ets_30_pct_gdp":"ETS Compliance Costs in 2030 (%GDP)",

    # NZF Compliance Costs (BAU Only)
    "bau_usd_23_recon":"BAU Costs in 2023 (US$)", 
    "bau_usd_30_recon":"BAU Costs in 2030 (US$)", 
    "bau_usd_40_recon":"BAU Costs in 2040 (US$)", 
    "bau_usd_50_recon":"BAU Costs in 2050 (US$)",
    "bau_23_pct_gdp":"BAU Costs in 2023 (%GDP)", 
    "bau_30_pct_gdp":"BAU Costs in 2030 (%GDP)", 
    "bau_40_pct_gdp":"BAU Costs in 2040 (%GDP)", 
    "bau_50_pct_gdp":"BAU Costs in 2050 (%GDP)", 

    # NZF Compliance Costs (S24 delta from BAU)
    "s24_usd_23_recon_del":"NZF Incremental Cost in 2023 (US$)", 
    "s24_usd_30_recon_del":"NZF Incremental Cost in 2030 (US$)", 
    "s24_usd_40_recon_del":"NZF Incremental Cost in 2040 (US$)", 
    "s24_usd_50_recon_del":"NZF Incremental Cost in 2050 (US$)",
    "s24_del_23_pct_gdp":"NZF Incremental Cost in 2023 (%GDP)", 
    "s24_del_30_pct_gdp":"NZF Incremental Cost in 2030 (%GDP)", 
    "s24_del_40_pct_gdp":"NZF Incremental Cost in 2040 (%GDP)", 
    "s24_del_50_pct_gdp":"NZF Incremental Cost in 2050 (%GDP)"
}

impact_res_ex = pd.read_csv(
    "https://raw.githubusercontent.com/james-stewart-808/inventory-tracker/main/datasets/impact_analysis_ex.csv",
    dtype={"source_iso_code":"str"}
).rename(columns=impact_res_ex_r)

impact_res_ex_so = impact_res_ex.sort_values(by="NZF Incremental Cost in 2050 (%GDP)", ascending=False).reset_index(drop=True)
impact_res_ex_cou = impact_res_ex_so[(impact_res_ex_so.source_iso_code == st.session_state.iso_code)]
impact_res_ex_cou_rank = impact_res_ex_cou.index.values[0]+1

st.title("Key Impact Tracking Results for {0}".format(st.session_state.iso_country))
st.header("General Results")

ETS_NZF = st.segmented_control(
    "Are you interested in econonic impacts from the EU ETS, IMO NZF, or both?",
    ["EU ETS", "IMO NZF", "Combined"])
if ETS_NZF == None:
    ETS_NZF = "EU ETS"


if ETS_NZF == "EU ETS":
    
    st.altair_chart("Top 25 Countries in terms of Impacts Generated by the EU ETS in 2030 - by % share of GDP")
    alt.Chart(impact_res_ex_so.sort_values(by="ETS Compliance Costs in 2030 (%GDP)", ascending=False).iloc[:25]).mark_bar().encode(
        x=alt.X("Country"),#, sort='-y'),
        y=alt.Y("ETS Compliance Costs in 2030 (%GDP)"),
        color="ETS Compliance Costs in 2030 (%GDP)")

    #st.caption("EU ETS costs for {0}.".format(st.session_state.iso_country))

"""

tot_mtc_cost_usd = np.round(impact_res["Total MTC Costs (US$)"].sum() / 1000000000, 1)
tot_com_cost_usd = np.round(impact_res["Compliance Costs (US$)"].sum() / 1000000000, 1)
st.markdown(" - Overall, 81.9 million tonnes of CO2 (around 15%), USD{0}bn in Maritime Transport Costs and USD{1}bn in Compliance Costs associated with NZF (assuming 2033 GFI values) are mapped onto 5.4bn tonnes and USD4.7tn of the Seaborne TandT data for 2018.".format(tot_mtc_cost_usd, tot_com_cost_usd))

com_tot_usd_nat_ave = np.round(impact_res["Compliance Costs (US$)"].mean() / 1000000, 1)
st.markdown(" - On average, countries would have paid ${0}m in compliance costs across their import and export trade portfolios in 2018.".format(com_tot_usd_nat_ave))

com_tot_usd_nat_ave = np.round(impact_res["Compliance Costs (%GDP)"].mean(), 3)
com_tot_usd_nat_min = np.round(impact_res["Compliance Costs (%GDP)"].min(), 3)
com_tot_usd_nat_max = np.round(impact_res["Compliance Costs (%GDP)"].max(), 3)
st.markdown(" - Compliance costs associated with Imports and Exports would have equated to {0}% of national GDP on average across all countries in 2018, ranging from {1}% - {2}% of GDP.".format(com_tot_usd_nat_ave, com_tot_usd_nat_min, com_tot_usd_nat_max))

st.caption("Top 25 Countries in terms of Impacts Generated by the IMO NZF - by % share of GDP")
st.altair_chart(
    alt.Chart(impact_res.sort_values(by="Compliance Costs (%GDP)", ascending=False).iloc[:25]).mark_bar().encode(
        x=alt.X("Country", sort='-y'),
        y=alt.Y("Compliance Costs (%GDP)"),
        color="Compliance Costs (%GDP)"))


st.subheader("The section below provides facility to explore the results of the Impact Tracking Architecture for 2018.")
country_stats_iso = pd.read_csv("https://raw.githubusercontent.com/james-stewart-808/inventory-tracker/main/datasets/country_status_labels_v3.csv", dtype={"iso_code":"str"})
coun_results_cl_iso = pd.merge(country_stats_iso, impact_res, left_on="iso_code", right_on="code_str3", how='right')

# Regional Aggregation
st.caption("Regional Aggregation of Impacts Generated by the IMO NZF - by % share of GDP")
coun_results_cl_iso_region = coun_results_cl_iso.groupby(["region"]).agg({"Compliance Costs (%GDP)":"mean"}).reset_index().sort_values(by="Compliance Costs (%GDP)", ascending=False)
st.altair_chart(
    alt.Chart(coun_results_cl_iso_region.sort_values(by="Compliance Costs (%GDP)", ascending=False).iloc[:25]).mark_bar().encode(
        x=alt.X("region", sort='-y'),
        y=alt.Y("Compliance Costs (%GDP)"),
        color="Compliance Costs (%GDP)"))

# Region & Development Status Aggregation
st.caption("Region & Development Aggregation of Impacts Generated by the IMO NZF - by % share of GDP")
coun_results_cl_iso["reg_status"] = coun_results_cl_iso.region + " - " + coun_results_cl_iso.status
coun_results_cl_iso_reg_status = coun_results_cl_iso.groupby(["reg_status"]).agg({"Compliance Costs (%GDP)":"mean"}).reset_index().sort_values(by="Compliance Costs (%GDP)", ascending=False)
st.altair_chart(
    alt.Chart(coun_results_cl_iso_reg_status.sort_values(by="Compliance Costs (%GDP)", ascending=False).iloc[:25]).mark_bar().encode(
        x=alt.X("reg_status", sort='-y'),
        y=alt.Y("Compliance Costs (%GDP)"),
        color="Compliance Costs (%GDP)"))

# Development Status Aggregation
st.caption("Development of Impacts Generated by the IMO NZF - by % share of GDP")
coun_results_cl_iso_status = coun_results_cl_iso.groupby(["status"]).agg({"Compliance Costs (%GDP)":"mean"}).reset_index().sort_values(by="Compliance Costs (%GDP)", ascending=False)
st.altair_chart(
    alt.Chart(coun_results_cl_iso_status.sort_values(by="Compliance Costs (%GDP)", ascending=False).iloc[:25]).mark_bar().encode(
        x=alt.X("status", sort='-y'),
        y=alt.Y("Compliance Costs (%GDP)"),
        color="Compliance Costs (%GDP)"))


# Results by HS2 Commodity Heading
impact_HS2_res_r = {
    "MTC_usd":"Total MTC Costs (US$)",
    "MTC_per_value_pct":"Total MTC Costs (%ad-val)",
    "com_tot_usd":"Compliance Costs (US$)",
    "com_tot_usd_per_value_pct":"Compliance Costs (%ad-val)"
}
impact_HS2_res = pd.read_csv("https://raw.githubusercontent.com/james-stewart-808/inventory-tracker/main/datasets/TandT_MTC_info_HS4_results.csv", dtype={"HS2":"str"}).rename(columns=impact_HS2_res_r)
impact_HS2_res["Description"] = [impact_HS2_res.HS2[i] + " - " + impact_HS2_res.description[i][:10] for i in range(impact_HS2_res.shape[0])]

st.caption("Top 25 Commodities (by HS2) in terms of Impacts Generated by the IMO NZF - by 'Ad-valorem' percentage of Trade Value")
st.altair_chart(
    alt.Chart(impact_HS2_res.sort_values(by="Compliance Costs (%ad-val)", ascending=False).iloc[:25]).mark_bar().encode(
        x=alt.X("Description", sort='-y'),
        y=alt.Y("Compliance Costs (%ad-val)"),
        color="Compliance Costs (%ad-val)"))




st.header("Results for {0}".format(st.session_state.iso_country))

com_tot_usd_nat_coun_exp = np.round(impact_res_cou["Exporter-side Compliance Costs (US$)"].sum() / 1000000, 2)
com_tot_usd_nat_coun_imp = np.round(impact_res_cou["Importer-side Compliance Costs (US$)"].sum() / 1000000, 2)
com_tot_usd_nat_coun = np.round(impact_res_cou["Compliance Costs (US$)"].sum() / 1000000, 2)
st.markdown(" - Compliance costs associated with {0}'s merchandise trade would have totalled USD{1}m for exported goods and USD{2}m for imported goods in 2018, amounting to USD{3}m in total.".format(st.session_state.iso_country, com_tot_usd_nat_coun_exp, com_tot_usd_nat_coun_imp, com_tot_usd_nat_coun))

com_tot_usd_nat_coun_pct_gdp = impact_res_cou["Compliance Costs (%GDP)"].values[0]
st.markdown(" - Compliance costs associated with {0}'s merchandise trade would have amounted to {1}% of it's national GDP that year, ranking it {2} of {3} countries".format(st.session_state.iso_country, com_tot_usd_nat_coun_pct_gdp, impact_res_cou_rank, impact_res.shape[0]))

st.caption("Full impact tracking results for {0} are presented below.".format(st.session_state.iso_country))
st.write(impact_res_cou.iloc[0])

"""




#
